### ISSUE TITLE
Why is "ox" removed from the word "Oxford"

### ISSUE THREAD

**Issue by azmatzuberi** [Richdark/RAKE-PHP#1]
Hi,

I'm having an issue with this algorithm, where it removes "ox" from the word "Oxford" which ends up like: "ford"

Same goes with some words with "ex" in the beginning. 

Any clues on how to fix this?

**Comment by Richdark** [comment]
Hi, I haven't been working with the algorithm for a while, I cannot give you a quick answer. I'll try to look at it during weekend and let you know afterwards.

**Comment by Richdark** [comment]
Looks like UTF8 literals should be written with uppercase 'X'. I fixed it, it's working fine now (checked under PHP 5.5.9 on Ubuntu). Also, if you use PHP7, I found that this version introduced [new codepoint syntax](https://secure.php.net/manual/en/migration70.new-features.php#migration70.new-features.unicode-codepoint-escape-syntax). Let me know if problem persists.
